# 导航目标位姿（由 launch 合并进 pb2025_sentry_behavior_server）
# 黑板键与下列名称一致：goal_pose="{@supply}" 等
pb2025_sentry_behavior_server:
  ros__parameters:
    supply:  # 补给区
      frame_id: "map"
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        w: 1.0

    fort:  # 堡垒 
      frame_id: "map"
      position:
        x: 0.75
        y: 1.80
        z: 0.0
      orientation:
        w: 1.0
    
    fort_out:  # 堡垒出口侧  
      frame_id: "map"
      position:
        x: 2.00
        y: 0.00
        z: 0.0
      orientation:
        w: 1.0

    ramp_base:  # 斜坡坡底 
      frame_id: "map"
      position:
        x: 2.32
        y: -1.70
        z: 0.0
      orientation:
        w: 1.0

    ramp_top:  # 斜坡坡顶  
      frame_id: "map"
      position:
        x: -0.50
        y: -1.70
        z: 0.0
      orientation:
        w: 1.0

    highway_in:  # 公路入口侧
      frame_id: "map"
      position:
        x: -0.10
        y: -3.15
        z: 0.0
      orientation:
        w: 1.0

    highway_in_far:  # 公路入口侧远处
      frame_id: "map"
      position:
        x: -0.8
        y: -3.15
        z: 0.0
      orientation:
        w: 1.0    

    highway_out:  # 公路出口侧
      frame_id: "map"
      position:
        x: 2.80
        y: -3.30
        z: 0.0
      orientation:
        w: 1.0

    highland_in:  # 高地入口侧
      frame_id: "map"
      position:
        x: 4.5
        y: -3.15
        z: 0.0
      orientation:
        w: 1.0

    highland:  # 高地
      frame_id: "map"
      position:
        x: 5.0
        y: -1.5
        z: 0.0
      orientation:
        w: 1.0

    outpost:  # 前哨
      frame_id: "map"
      position:
        x: 6.0
        y: -0.5
        z: 0.0
      orientation:
        w: 1.0

    highland_my:  # 我方高地点
      frame_id: "map"
      position:
        x: 4.5
        y: 0.0
        z: 0.0
      orientation:
        w: 1.0

    outpost_my:  # 我方前哨点
      frame_id: "map"
      position:
        x: 5.0
        y: -2.0
        z: 0.0
      orientation:
        w: 1.0        