name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: Build standard_robot_pp_ros2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: standard_robot_pp_ros2
          target-ros2-distro: humble
          vcs-repo-file-url: "${{ github.workspace }}/dependencies.repos"
          skip-tests: true

      - name: Test standard_robot_pp_ros2
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh standard_robot_pp_ros2
